*** Variables ***
${open_account_button}    css=button[aria-label='Go to user profile']
${open_privacy_&_security_button}    css=button[aria-label='Show Privacy and Security Menu']
${go_to_change_password_button}    css=button[aria-label='Go to change password page']
${current_password_input}    id=currentPassword
${new_password_input}    id=newPassword
${repeat_new_password_input}    id=newPasswordRepeat
${change_password_button}    id=changeButton

