name: Robot Framework Allure Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-robotframework

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          tar -zxvf allure-2.29.0.tgz
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Wait for Juice Shop
        run: |
          for i in {1..90}; do
            if curl -s http://127.0.0.1:3000/rest/products/search?q=apple | grep -qi "apple"; then
              echo "Juice Shop API is ready"
              sleep 5
              exit 0
            fi
            echo "Waiting for Juice Shop API..."
            sleep 2
          done
          exit 1

      - name: Run Robot tests
        continue-on-error: true
        env:
          BASE_URL: http://127.0.0.1:3000
          REGISTRATION_URL: http://127.0.0.1:3000/#/register
          LOGIN_URL: http://127.0.0.1:3000/#/login
          VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
          BROWSER: chrome
          HEADLESS: true
        run: |
          mkdir -p results reports/allure/allure-results reports/allure/allure-report
          robot \
            --listener allure_robotframework:reports/allure/allure-results \
            --outputdir results \
            --exclude performance \
            --exclude security \
            tests/02_ui/02_products_tests.robot

      - name: Generate Allure report
        run: |
          allure generate reports/allure/allure-results --clean -o reports/allure/allure-report

      - name: Upload Robot logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: |
            results/
            reports/allure/allure-results/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Allure report to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/allure/allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4