name: Robot Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Install Microsoft Edge
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge.list
          sudo apt update
          sudo apt install microsoft-edge-stable

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Wait for Juice Shop
        run: |
          for i in {1..60}; do
            if curl -s http://127.0.0.1:3000 > /dev/null; then
              echo "Juice Shop is up"
              exit 0
            fi
            echo "Waiting for Juice Shop..."
            sleep 2
          done
          exit 1

      - name: Run UI/API/DB Robot tests
        env:
          BASE_URL: http://127.0.0.1:3000
          REGISTRATION_URL: "http://localhost:3000/#/register"
          LOGIN_URL: "http://127.0.0.1:3000/#/login"
          VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
          BROWSER: edge
          HEADLESS: true
        run: |
          mkdir -p results
          robot \
            --outputdir results \
            --variable BASE_URL:http://127.0.0.1:3000 \
            --variable REGISTRATION_URL:"http://localhost:3000/#/register" \
            --variable LOGIN_URL:"http://127.0.0.1:3000/#/login" \
            --variable HEADLESS:false \
            --exclude performance \
            --exclude security \
            tests/01_ui/02_products_tests.robot

      - name: Upload Robot Framework reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: |
            results/log.html
            results/report.html
            results/output.xml
            results/*.png